---
- hosts: "{{ hosts_group }}"
  tasks:
    - name: "Copy files"
      ansible.builtin.copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        force: yes
        mode: '0777'
...