---
- hosts: "{{ hosts_group }}"
  tasks:
    - name: "Copy files"
      ansible.builtin.copy:
        src: "/files/infoclinika_templates/"
        dest: "/mnt/data/infodent/i25/"
        owner: "nobody"
        group: "nogroup"
        force: yes
        mode: '0777'
...