---
- hosts: "all"
  tasks:
    - name: "Add an /etc/hosts entry for your IP address"
      ansible.builtin.template:
        src: "/root/playbooks/template/hosts"
        dest: "/etc/hosts"
        backup: "yes"
    
    - name: "Add the Proxmox VE repository key as root"
      command: "wget https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg"  

    - name: add pve-no-subscription repo
      apt_repository:
        repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
        state: present
        filename: 'pve-install-repo'

    - name: "Update your repository and system by running:"
      apt:
        update_cache: "yes"
        upgrade: "dist"
    
    - name: "/etc/network/interfaces edit"
      ansible.builtin.template:
        backup: "yes"
        src: "/root/playbooks/template/interfaces"
        dest: "/etc/network/interfaces"
        owner: root
        group: root
        mode: 0644

    - name: "Install the Proxmox VE packages"
      apt:
        name: "{{ item }}"
        state: "latest"
        install_recommends: "yes"
      with_items:
      - proxmox-ve
      - postfix
      - open-iscsi
      - bridge-utils
    
    - name: "Remove the os-prober Package"
      apt:
        name: "os-prober"
        state: "absent"

    - name: search for standard kernels
      shell: "$( which dpkg ) --get-selections linux-image* | $( which grep ) -i install | $(which awk) '{print $1}'"
      args:
        executable: /bin/bash
      register: standart_kernels_installed

    - name: remove standart kernels
      apt:
        name: "{{ item }}"
        state: absent
      with_items: "{{ standart_kernels_installed.stdout_lines|default([]) }}"

    - name: "rebooting the server"
      shell: nohup bash -c "sleep 2s && reboot" &
      async: 0
      poll: 0
      ignore_errors: yes
      register: reboot
      tags: reboot

    - name: waiting for server to come back
      local_action: wait_for host={{ proxmox_ip }} state=started
      when: reboot.changed
      async: 2400
      poll: 10
      tags: reboot
...
