---
- hosts: "debian_test"
  become: true
  become_method: "su"
  become_user: "root"
  tasks:
    - name: Set authorized key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
...
