- name: Example play
  hosts: "{{ hosts_group }}"
  gather_facts: no  # gather facts AFTER the host key has been accepted instead
  tasks:
  - name: Accept EC2 SSH host keys
    connection: local
    become: false
    shell: |
      ssh-keygen -F {{ inventory_hostname }} ||
        ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
    register: known_hosts_script
    changed_when: "'found' not in known_hosts_script.stdout"