---
- hosts: "{{ hosts_group }}"
  tasks:
    - name: Restart a service
      ansible.windows.win_service:
        name: "{{ item }}"
        state: restarted
      with_items:
      - Spooler
      - SEMgrSvc
...