---
- hosts: "debian_test"
  become: true
  become_method: "su"
  become_user: "root"
  tasks:
    - name: "change sshd_condfig"
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "(#P|P)ermitRootLogin.*"
        line: "PermitRootLogin yes"
        state: "present"
    - name: "reboot sshd"
      service:
        name: "sshd"
        state: "reloaded"
...
