---
- hosts: "{{ hosts_group }}"
  vars:
    kernel: "{{ ansible_kernel_version }}"
    os: "{{ ansible_os_family }}" 
    release: "{{ ansible_lsb.release }}"
  tasks:
    - name: "config debian repository"
      lineinfile:
        path: "/etc/apt/sources.list"
        regex: "{{ item.reg }}"
        line: "{{ item.line }}"
      with_items:
      - {reg: "deb http.* bullseye main", line: "deb http://repo.sadkomed.local/debian bullseye main"}
      - {reg: "deb-src http.* bullseye main", line: "deb-src http://repo.sadkomed.local/debian bullseye main"}
      - {reg: "deb http.* bullseye-security main contrib non-free", line: "deb http://repo.sadkomed.local/debian-security bullseye-security main contrib non-free"}
      - {reg: "deb-src http.* bullseye-security main contrib non-free", line: "deb-src http://repo.sadkomed.local/debian-security bullseye-security main contrib non-free"}
      - {reg: "deb http.* bullseye-updates main contrib non-free", line: "deb http://repo.sadkomed.local/debian/ bullseye-updates main contrib non-free"}
      - {reg: "deb-src http.* bullseye-updates main contrib non-free", line: "deb-src http://repo.sadkomed.local/debian/ bullseye-updates main contrib non-free"}
      when: os == "Debian" and release == "11"
    
    - name: "config proxmox repository"
      lineinfile:
        path: "/etc/apt/sources.list.d/pve-install-repo.list"
        regex: "deb \[arch=amd64].*bullseye pve-no-subscription"
        line: "deb [arch=amd64] http://repo.sadkomed.local/pve bullseye pve-no-subscription"
      when: kernel | regex_search(".*PVE.*")
...