---
- hosts: "{{ hosts_group }}"
  tasks:
    - name: add f99_fw_kdl in config
      lineinfile:
        dest: "/etc/tinc/sadkomed_ix/hosts/f99_fw"
        regexp: 'Address = 89.109.52.229'
        line: 'Address = 95.172.55.226'
        backup: "yes"
    - name: 'Reboot Tinc service'
      service:
        name: 'tinc.service'
        state: 'restarted'
...